version: '2'
services:
  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: kibana
    hostname: kibana
    restart: unless-stopped
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    environment:
      SERVER_NAME: $SERVER_NAME
      ELASTICSEARCH_URL: $ELASTICSEARCH_URL
      SERVER_HOST: $SERVER_HOST
